---
# file: roles/logstash/tasks/main.yml
- name: upgrade logstash
  import_tasks: upgrade.yml
  when: upgrade is defined

- name: logstash install
  package:
    name: "{{ (logstash_version == '') | ternary('logstash',['logstash', logstash_version]|join('-')) }}"
    state: present
  register: result
  until: result is success
  retries: 3
  delay: 5

- name: logstash plugin install
  shell: |
    /usr/share/logstash/bin/logstash-plugin install {{ item.plugin }}
  args:
    creates: "{{ item.creates }}"
  with_items: "{{ logstash_plugins }}"
  register: result
  until: result is success
  retries: 3
  delay: 5
