---
# file: roles/logstash/tasks/upgrade.yml
- name: logstash plugin remove
  shell: |
    /usr/share/logstash/bin/logstash-plugin remove {{ item.plugin }}
  with_items: "{{ logstash_plugins }}"

- name: remove logstash plugin check file
  file:
    path: "{{ item.plugin }}"
    state: absent
  with_items: "{{ logstash_plugins }}"
