---
# defaults file for elasticsearch
es_cluster_name: 'escluster'
xpack_security_enabled: False
xpack_monitoring_enabled: True
xpack_graph_enabled: False
xpack_watcher_enabled: False
xpack_reporting_enabled: False
xpack_ml_enabled: False
