---
# defaults file for elasticsearch
elasticsearch_version: ''
elasticsearch_plugins:
  - { plugin: 'analysis-icu', creates: '/usr/share/elasticsearch/plugins/analysis-icu' }
  - { plugin: 'analysis-kuromoji', creates: '/usr/share/elasticsearch/plugins/analysis-kuromoji' }
  - { plugin: 'ingest-geoip', creates: '/usr/share/elasticsearch/plugins/ingest-geoip' }
  - { plugin: 'ingest-user-agent', creates: '/usr/share/elasticsearch/plugins/ingest-user-agent' }
es_cluster_name: 'escluster'
es_mx: "{{ ansible_memtotal_mb // 2 }}"
es_ms: "{{ ansible_memtotal_mb // 2 }}"
es_external_disk:
  - { disk: "", path: "" }
xpack_apm_enabled: True
xpack_grokdebugger_enabled: True
xpack_searchprofiler_enabled: True
xpack_ml_enabled: True
xpack_monitoring_enabled: True
xpack_monitoring_collection_enabled: True
