---
# file: all.yml
- hosts:
    - elk
    - aio_standalone
  roles:
    - { role: common, when: exec_common_role}
    - elk-common
    - elasticsearch
    - curator
    - kibana
    - logstash

  environment:
    - "{{ proxy_env }}"
    - ES_JAVA_OPTS: "-Dhttps.proxyHost={{ proxy_env.https_proxy|default('')|regex_replace('^https*://([0-9.]*).*$', '\\1') }} -Dhttps.proxyPort={{ proxy_env.https_proxy|default('')|regex_replace('^https*://.*:([0-9]*)$', '\\1') }}"

- hosts: elasticsearch
  roles:
    - { role: common, when: exec_common_role}
    - elk-common
    - elasticsearch
    - curator

  environment:
    - "{{ proxy_env }}"
    - ES_JAVA_OPTS: "-Dhttps.proxyHost={{ proxy_env.https_proxy|default('')|regex_replace('^https*://([0-9.]*).*$', '\\1') }} -Dhttps.proxyPort={{ proxy_env.https_proxy|default('')|regex_replace('^https*://.*:([0-9]*)$', '\\1') }}"

- hosts: kibana
  roles:
    - { role: common, when: exec_common_role}
    - elk-common
    - kibana

  environment:
    - "{{ proxy_env }}"
    - ES_JAVA_OPTS: "-Dhttps.proxyHost={{ proxy_env.https_proxy|default('')|regex_replace('^https*://([0-9.]*).*$', '\\1') }} -Dhttps.proxyPort={{ proxy_env.https_proxy|default('')|regex_replace('^https*://.*:([0-9]*)$', '\\1') }}"

- hosts: logstash
  roles:
    - { role: common, when: exec_common_role}
    - elk-common
    - logstash

  environment:
    - "{{ proxy_env }}"
    - ES_JAVA_OPTS: "-Dhttps.proxyHost={{ proxy_env.https_proxy|default('')|regex_replace('^https*://([0-9.]*).*$', '\\1') }} -Dhttps.proxyPort={{ proxy_env.https_proxy|default('')|regex_replace('^https*://.*:([0-9]*)$', '\\1') }}"
