---
# file: roles/kibana/tasks/main.yml
- name: upgrade kibana
  import_tasks: upgrade.yml
  when: upgrade is defined

- name: kibana install
  package:
    name: "{{ (kibana_version == '') | ternary('kibana',['kibana', kibana_version]|join('-')) }}"
    state: present
  register: result
  until: result is success
  retries: 3
  delay: 5

- name: kibana plugin install
  shell: |
    /usr/share/kibana/bin/kibana-plugin install {{ item.plugin }}
  args:
    creates: "{{ item.creates }}"
  become: true
  become_user: kibana
  become_method: sudo
  notify: kibana restart
  with_items: "{{ kibana_plugins }}"
  register: result
  until: result is success
  retries: 3
  delay: 5
  when: kibana_plugins is not none

- name: create kibana pid dir
  file:
    path: /var/run/kibana
    state: directory
    owner: kibana
    group: kibana
    mode: 0755

- name: create kibana log dir
  file:
    path: /var/log/kibana
    state: directory
    owner: kibana
    group: kibana
    mode: 0755

- block:
  - name: kibana config setting
    template:
      src: kibana.yml.j2
      dest: /etc/kibana/kibana.yml
      owner: root
      group: root
      mode: 0664
      backup: yes
    register: is_kibana_setting
    notify: kibana restart

  - name: kibana logrotate setting
    copy:
      src: etc_logrotate.d_kibana
      dest: /etc/logrotate.d/kibana
      owner: root
      group: root
      mode: 0644
      backup: yes
    register: is_kibana_logrotate_setting

  - name: kibana tmpfiles.d setting
    copy:
      src: kibana.conf
      dest: /etc/tmpfiles.d/kibana.conf
      owner: root
      group: root
      mode: 0644
      backup: yes
    register: is_kibana_tmpfiles_d_setting

  always:
  - name: elk-common backup settings
    include_tasks: backup.yml
    with_flattened:
      - "{{ is_kibana_setting|default() }}"
      - "{{ is_kibana_logrotate_setting|default() }}"
      - "{{ is_kibana_tmpfiles_d_setting|default() }}"
    loop_control:
      loop_var: backup_item

- name: enable kibana service
  service:
    name: kibana.service
    state: started
    enabled: yes
    daemon_reload: yes
