---
# file: roles/kibana/tasks/main.yml
- name: kibana install
  package: name=kibana state=latest

- block:
  - name: kibana config setting
    copy: >
      src=kibana.yml
      dest=/etc/kibana
      owner=root
      group=root
      mode=0664
      backup=yes
    register: is_kibana_setting
    notify: kibana restart

  always:
  - name: elk-common backup settings
    include: backup.yml
    with_flattened:
      - "{{ is_kibana_setting|default() }}"
    loop_control:
      loop_var: backup_item

- name: enable kibana service
  service: name=kibana state=started enabled=yes daemon_reload=yes
