---
# file: roles/kibana/tasks/upgrade.yml
- name: disable kibana service
  service:
    name: kibana
    state: stopped
    enabled: no

- name: kibana plugin remove
  shell: |
    /usr/share/kibana/bin/kibana-plugin remove {{ item.plugin }}
  with_items: "{{ kibana_plugins }}"
  when: kibana_plugins is not none

- name: kibana remove
  package:
    name: kibana
    state: absent
