---
# file: roles/elk-common/tasks/main.yml
- name: register subscription and yum proxy setting
  import_tasks: yum_setup.yml

- block:
  - name: enable elastic repo
    copy:
      src: elastic.repo
      dest: /etc/yum.repos.d/elastic.repo
      owner: root
      group: root
      mode: 0644
      backup: yes
    register: is_elastic_repo_setting

  always:
  - name: elk-common backup settings
    include_tasks: backup.yml
    with_flattened:
      - "{{ is_elastic_repo_setting|default() }}"
    loop_control:
      loop_var: backup_item

- name: jdk install
  package:
    name: "{{item}}"
    state: latest
    enablerepo: "{{ (ansible_distribution == 'RedHat') | ternary('rhel-7-server-debug-rpms','base-debuginfo') }}"
  register: result
  until: result | success
  retries: 3
  delay: 5
  with_items:
    - java-1.8.0-openjdk-devel
    - java-1.8.0-openjdk-debuginfo
    - tzdata-java
  when: >
    rhel_subscription_enabled and
    ( 'elk' in group_names or
    'elasticsearch' in group_names or
    'logstash' in group_names or
    'aio_standalone' in group_names )
