---
# tasks file for curator
- block:
  - name: enable curator repo
    copy:
      src: curator.repo
      dest: /etc/yum.repos.d/curator.repo
      owner: root
      group: root
      mode: 0644
      backup: yes
    register: is_curator_repo_setting

  always:
  - name: curator backup settings
    include_tasks: backup.yml
    with_flattened:
      - "{{ is_curator_repo_setting|default() }}"
    loop_control:
      loop_var: backup_item

- name: upgrade curator
  import_tasks: upgrade.yml
  when: "{{ upgrade|default('false') }}"

- name: curator install
  package:
    name: "{{ (curator_version == '') | ternary('elasticsearch-curator',['elasticsearch-curator', curator_version]|join('-')) }}"
    state: present
  register: result
  until: result | success
  retries: 3
  delay: 5
