---
# file: roles/elasticsearch/tasks/main.yml
- name: elasticsearch install
  package: name=elasticsearch state=latest

- name: elasticsearch x-pack plugin install
  shell: >
    /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch x-pack
    creates=/usr/share/elasticsearch/plugins/x-pack/plugin-descriptor.properties
  notify: elasticsearch restart

- name: elasticsearch analysis-icu plugin install
  shell: >
    /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch analysis-icu
    creates=/usr/share/elasticsearch/plugins/analysis-icu/plugin-descriptor.properties
  notify: elasticsearch restart

- name: elasticsearch analysis-kuromoji plugin install
  shell: >
    /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch analysis-kuromoji
    creates=/usr/share/elasticsearch/plugins/analysis-kuromoji/plugin-descriptor.properties
  notify: elasticsearch restart

- name: elasticsearch ingest-geoip plugin install
  shell: >
    /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch ingest-geoip
    creates=/usr/share/elasticsearch/plugins/ingest-geoip/plugin-descriptor.properties
  notify: elasticsearch restart

- block:
  - name: create elasticsearch systemd dir
    file: >
      path="/etc/systemd/system/elasticsearch.service.d"
      state=directory
      owner=root
      group=root
      mode=0755

  - name: elasticsarch systemd setting
    copy: >
      src=limit_memlock.conf
      dest=/etc/systemd/system/elasticsearch.service.d
      owner=root
      group=root
      mode=0644
      backup=yes
    register: is_elasticsearch_systemd_setting
    notify: elasticsearch restart

  - name: elasticsarch config setting
    template: >
      src=elasticsearch.yml.j2
      dest=/etc/elasticsearch/elasticsearch.yml
      owner=root
      group=elasticsearch
      mode=0660
      backup=yes
    register: is_elasticsearch_setting
    notify: elasticsearch restart

  - name: elasticsarch jvm setting
    template: >
      src=jvm.options.j2
      dest=/etc/elasticsearch/jvm.options
      owner=root
      group=elasticsearch
      mode=0664
      backup=yes
    register: is_elasticsearch_jvm_setting
    notify: elasticsearch restart

  always:
  - name: elk-common backup settings
    include: backup.yml
    with_flattened:
      - "{{ is_elasticsearch_systemd_setting|default() }}"
      - "{{ is_elasticsearch_setting|default() }}"
      - "{{ is_elasticsearch_jvm_setting|default() }}"
    loop_control:
      loop_var: backup_item

- name: enable elasticsearch service
  service: name=elasticsearch state=started enabled=yes daemon_reload=yes
