---
# file: roles/elasticsearch-kibana/tasks/main.yml
- name: packages install
  yum: name={{item}} state=present
  with_items:
    - java-1.7.0-openjdk

- name: elasticsearch check
  command: rpm -q elasticsearch
  register: is_elasticsearch_installed
  failed_when: is_elasticsearch_installed.rc not in [0,1]
  changed_when: is_elasticsearch_installed.rc != 0

- name: elasticsearch install
  yum: name={{item}} state=present
  with_items:
    - "{{ elasticsearch_rpm }}"
  when: is_elasticsearch_installed.rc == 1

- name: elasticsarch startup setting
  template: src=etc_sysconfig_elasticsearch.j2 dest=/etc/sysconfig/elasticsearch owner=root group=root mode=0644
  notify: elasticsearch restart

- name: elasticsarch config setting
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644
  notify: elasticsearch restart

- name: create kibana_user
  user: name="{{ kibana_user }}" shell=/bin/false

- name: create opt dir
  file: path=/opt state=directory mode=0755

- name: kibana check
  command: ls /opt/kibana
  register: is_kibana_installed
  failed_when: is_kibana_installed.rc not in [0,2]
  changed_when: is_kibana_installed.rc != 0

- name: get kibana
  get_url: url="{{ kibana_pkg }}" dest=/tmp/kibana4
  when: is_kibana_installed.rc == 2

- name: extract kibana
  unarchive: src=/tmp/kibana4 dest=/opt copy=no owner="{{ kibana_user }}" group="{{ kibana_user }}"
  when: is_kibana_installed.rc == 2

- name: kibana extract check
  shell: ls -d /opt/kibana-*
  register: is_kibana_extracted
  changed_when: is_kibana_extracted.rc != 0

- name: current kibana link
  file: src={{ is_kibana_extracted.stdout }} dest=/opt/kibana state=link

- name: chown kibana dir
  file: path=/opt/kibana/ owner="{{ kibana_user }}" group="{{ kibana_user }}" recurse=yes

- name: kibana config setting
  template: src=kibana.yml.j2 dest=/opt/kibana/config/kibana.yml owner="{{ kibana_user }}" group="{{ kibana_user }}" mode=0644
  notify: kibana restart

- name: kibana init script
  template: src=etc_init.d_kibana.j2 dest=/etc/init.d/kibana owner=root group=root mode=0755
  notify: kibana restart

- name: elasticsearch kibana service
  service: name={{item}} state=started enabled=yes
  with_items:
    - elasticsearch
    - kibana
