---
# file: roles/elasticsearch/tasks/main.yml
- name: elasticsearch install
  package: name=elasticsearch state=latest

- name: elasticsearch x-pack install
  shell: >
    /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch x-pack
    creates=/usr/share/elasticsearch/plugins/x-pack/NOTICE.txt

- block:
  - name: elasticsarch config setting
    template: >
      src=elasticsearch.yml.j2
      dest=/etc/elasticsearch/elasticsearch.yml
      owner=root
      group=elasticsearch
      mode=0660
      backup=yes
    register: is_elasticsearch_setting
    notify: elasticsearch restart

  - name: elasticsarch jvm setting
    template: >
      src=jvm.options.j2
      dest=/etc/elasticsearch/jvm.options
      owner=root
      group=elasticsearch
      mode=0664
      backup=yes
    register: is_elasticsearch_jvm_setting
    notify: elasticsearch restart

  always:
  - name: elk-common backup settings
    include: backup.yml
    with_flattened:
      - "{{ is_etc_sysconfig_elasticsearch_setting|default() }}"
      - "{{ is_elasticsearch_setting|default() }}"
      - "{{ is_elasticsearch_jvm_setting|default() }}"
    loop_control:
      loop_var: backup_item

- name: enable elasticsearch service
  service: name=elasticsearch state=started enabled=yes daemon_reload=yes
