---
# file: roles/elasticsearch/tasks/main.yml
- name: jdk install
  package: name={{item}} state=latest enablerepo="*debug*"
  with_items:
    - java-1.8.0-openjdk-devel
    - java-1.8.0-openjdk-debuginfo
    - tzdata-java

- name: elasticsearch install
  package: name=elasticsearch state=latest

- block:
  - name: elasticsarch startup setting
    template: >
      src=etc_sysconfig_elasticsearch.j2
      dest=/etc/sysconfig/elasticsearch
      owner=root
      group=root
      mode=0644
      backup=yes
    register: is_etc_sysconfig_elasticsearch_setting
    notify: elasticsearch restart

  - name: elasticsarch config setting
    template: >
      src=elasticsearch.yml.j2
      dest=/etc/elasticsearch/elasticsearch.yml
      owner=root
      group=elasticsearch
      mode=0660
      backup=yes
    register: is_elasticsearch_setting
    notify: elasticsearch restart

  - name: elasticsarch jvm setting
    template: >
      src=jvm.options.j2
      dest=/etc/elasticsearch/jvm.options
      owner=root
      group=elasticsearch
      mode=0664
      backup=yes
    register: is_elasticsearch_jvm_setting
    notify: elasticsearch restart

  always:
  - name: elk-common backup settings
    include: backup.yml
    with_flattened:
      - "{{ is_etc_sysconfig_elasticsearch_setting|default() }}"
      - "{{ is_elasticsearch_setting|default() }}"
      - "{{ is_elasticsearch_jvm_setting|default() }}"
    loop_control:
      loop_var: backup_item

- name: enable elasticsearch service
  service: name=elasticsearch state=started enabled=yes daemon_reload=yes
