---
# file: roles/elasticsearch/tasks/searchguard.yml
- name: elasticsearch version check
  shell: basename /usr/share/elasticsearch/lib/elasticsearch* | sed 's/.*-\(.*\).jar/\1/'
  register: elasticsearch_version
  changed_when: false

- name: elasticsearch search guard plugin install
  shell: |
    /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch com.floragunn:search-guard-{{ elasticsearch_version.stdout|regex_replace('\..*', '') }}:{{ elasticsearch_version.stdout }}-{{ searchguard_version }}
  args:
    creates: "/usr/share/elasticsearch/plugins/search-guard-{{ elasticsearch_version.stdout|regex_replace('\\..*', '') }}"
  notify: elasticsearch restart
  register: result
  until: result | success
  retries: 3
  delay: 5

- name: check truststore.jks
  stat:
    path: /etc/elasticsearch/truststore.jks
  register: truststore_stat

- block:
    - name: openssl install
      package:
        name: openssl
        state: present
      register: result
      until: result | success
      retries: 3
      delay: 5

    - name: create searchguard ca dir
      file:
        path: "{{ item.path }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode}}"
        state: directory
      with_items:
        - { path: "{{ searchguard_workdir }}/searchguard-ca", owner: 'root', group: 'root', mode: '0700' }
        - { path: "{{ searchguard_workdir }}/searchguard-ca/certs", owner: 'root', group: 'root', mode: '0700' }
        - { path: "{{ searchguard_workdir }}/searchguard-ca/db", owner: 'root', group: 'root', mode: '0700' }
        - { path: "{{ searchguard_workdir }}/searchguard-ca/private", owner: 'root', group: 'root', mode: '0700' }

    - name: create searchguard ca index file
      command: "touch {{ searchguard_workdir }}/searchguard-ca/db/{{ item.name }}.index"
      args:
        creates: "{{ searchguard_workdir }}/searchguard-ca/db/{{ item.name }}.index"
      with_items: "{{ searchguard_openssl_cnf }}"

    - name: create searchguard ca serial file
      shell: "openssl rand -hex 16 > {{ searchguard_workdir }}/searchguard-ca/db/{{ item.name }}.serial"
      args:
        creates: "{{ searchguard_workdir }}/searchguard-ca/db/serial"
      with_items: "{{ searchguard_openssl_cnf }}"

    - name: searchguard ca config setting
      template:
        src: ca.cnf.j2
        dest: "{{ searchguard_workdir }}/searchguard-ca/{{ item.name }}.cnf"
        owner: root
        group: root
        mode: 0660
      with_items: "{{ searchguard_openssl_cnf }}"

    - name: create searchguard ca private key and csr
      command: >
        openssl req -new
        -config {{ searchguard_workdir }}/searchguard-ca/{{ item.name }}.cnf
        -out {{ searchguard_workdir }}/searchguard-ca/{{ item.name }}.csr
        -keyout {{ searchguard_workdir }}/searchguard-ca/private/{{ item.name }}.key
        -batch
        -passout pass:password
      args:
        creates: "{{ searchguard_workdir }}/searchguard-ca/private/{{ item.name }}.key"
      with_items: "{{ searchguard_openssl_cnf }}"

    - name: create searchguard ca crt
      command: >
        openssl ca{% if item.root %} -selfsign{% endif %}
        -config {{ searchguard_workdir }}/searchguard-ca/root-ca.cnf
        -in {{ searchguard_workdir }}/searchguard-ca/{{ item.name }}.csr
        -out {{ searchguard_workdir }}/searchguard-ca/{{ item.name }}.crt
        -extensions {{ item.name|replace('-', '_') }}_ext
        -batch
        -passin pass:password
      args:
        creates: "{{ searchguard_workdir }}/searchguard-ca/{{ item.name }}.crt"
      with_items: "{{ searchguard_openssl_cnf }}"

    - name: create ca crt pem
      command: >
        openssl x509
        -in {{ searchguard_workdir }}/searchguard-ca/{{ item.name }}.crt
        -out {{ searchguard_workdir }}/searchguard-ca/{{ item.name }}.pem
        -outform PEM
      args:
        creates: "{{ searchguard_workdir }}/searchguard-ca/{{ item.name }}.pem"
      with_items: "{{ searchguard_openssl_cnf }}"

    - name: create truststore.jks
      command: >
        keytool -import
        -keystore {{ searchguard_workdir }}/searchguard-ca/truststore.jks
        -storepass password
        -noprompt
        -alias root-ca-chain
        -file {{ searchguard_workdir }}/searchguard-ca/root-ca.pem
      args:
        creates: "{{ searchguard_workdir }}/searchguard-ca/truststore.jks"

    - name: truststore store
      shell: "cat {{ searchguard_workdir }}/searchguard-ca/truststore.jks|base64 -w0"
      args:
        creates: /etc/elasticsearch/truststore.jks
      register: elasticsearch_truststore

    - name: chain-ca pem store
      shell: "cat {{ searchguard_workdir }}/searchguard-ca/signing-ca.pem {{ searchguard_workdir }}/searchguard-ca/signing-ca.pem|base64 -w0"
      args:
        creates: /etc/elasticsearch/keystore.jks
      register: elasticsearch_chain_ca_pem

    - name: delete searchguard ca dir
      file:
        path: "{{ searchguard_workdir }}/searchguard-ca"
        state: absent

  run_once: true
  when: not truststore_stat.stat.exists

- name: check keystore.jks
  stat:
    path: /etc/elasticsearch/keystore.jks
  register: keystore_stat

- block:
    - name: create keystore.jks
      command: >
        keytool -genkeypair
        -alias {{ ansible_hostname }}
        -keystore /etc/elasticsearch/keystore.jks
        -keyalg    RSA
        -keysize   2048
        -validity  3650
        -sigalg SHA256withRSA
        -keypass password
        -storepass password
        -dname "CN={{ ansible_nodename }},OU=client,O=client,C=JP"
        -ext "san=dns:{{ ansible_nodename }},ip:{{ ansible_default_ipv4.address }},dns:localhost,ip:127.0.0.1,oid:1.2.3.4.5.5"
      args:
        creates: /etc/elasticsearch/keystore.jks

    - name: create keystore csr
      command: >
        keytool -certreq
        -alias {{ ansible_hostname }}
        -keystore /etc/elasticsearch/keystore.jks
        -file /etc/elasticsearch/keystore.csr
        -keyalg    RSA
        -keypass password
        -storepass password
        -dname "CN={{ ansible_nodename }},OU=client,O=client,C=JP"
        -ext "san=dns:{{ ansible_nodename }},ip:{{ ansible_default_ipv4.address }},dns:localhost,ip:127.0.0.1,oid:1.2.3.4.5.5"

  when: not keystore_stat.stat.exists

- name: truststore deploy
  shell: "echo {{ elasticsearch_truststore.stdout|default() }}|base64 -d > /etc/elasticsearch/truststore.jks"
  args:
    creates: /etc/elasticsearch/truststore.jks
