---
# file: roles/elasticsearch/tasks/searchguard.yml
- name: elasticsearch version check
  shell: basename /usr/share/elasticsearch/lib/elasticsearch* | sed 's/.*-\(.*\).jar/\1/'
  register: elasticsearch_version
  changed_when: false

- name: elasticsearch search guard plugin install
  shell: |
    /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch com.floragunn:search-guard-{{ elasticsearch_version.stdout|regex_replace('\..*', '') }}:{{ elasticsearch_version.stdout }}-{{ searchguard_version }}
  args:
    creates: "/usr/share/elasticsearch/plugins/search-guard-{{ elasticsearch_version.stdout|regex_replace('\\..*', '') }}"
  notify: elasticsearch restart
  register: result
  until: result | success
  retries: 3
  delay: 5

- block:
    - name: openssl install
      package:
        name: openssl
        state: present
      register: result
      until: result | success
      retries: 3
      delay: 5

    - name: create searchguard ca dir
      file:
        path: "{{ item.path }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode}}"
        state: directory
      with_items:
        - { path: '/tmp/searchguard-ca', owner: 'root', group: 'root', mode: '0700' }
        - { path: '/tmp/searchguard-ca/certs', owner: 'root', group: 'root', mode: '0700' }
        - { path: '/tmp/searchguard-ca/db', owner: 'root', group: 'root', mode: '0700' }
        - { path: '/tmp/searchguard-ca/private', owner: 'root', group: 'root', mode: '0700' }

    - name: create searchguard ca index file
      file:
        path: '/tmp/searchguard-ca/db/index'
        owner: 'root'
        group: 'root'
        mode: '0600'
        state: directory

    - name: create searchguard ca serial file
      shell: "openssl rand -hex 16 > /tmp/searchguard-ca/db/serial"
      args:
        creates: /tmp/searchguard-ca/db/serial

    - name: create keystore.jks
      command: "keytool -genkeypair -keystore /tmp/keystore.jks -storepass 'password' -keypass 'password' -dname 'CN=kirk,OU=client,O=client,L=test, C=de' -validity 3650"
      args:
        creates: /etc/elasticsearch/keystore.jks

    - name: keystore check
      shell: "cat /tmp/keystore.jks|base64 -w0"
      args:
        creates: /etc/elasticsearch/keystore.jks
      register: elasticsearch_keystore
      changed_when: false

    - name: delete temporary keystore.jks
      file:
        path: /tmp/keystore.jks
        state: absent

  run_once: true

- name: keystore deploy
  shell: "echo {{ elasticsearch_keystore.stdout|default() }}|base64 -d > /etc/elasticsearch/keystore.jks"
  args:
    creates: /etc/elasticsearch/keystore.jks
