---
# file: roles/elasticsearch/tasks/search-guard.yml
- name: elasticsearch version check
  shell: basename /usr/share/elasticsearch/lib/elasticsearch* | sed 's/.*-\(.*\).jar/\1/'
  register: elasticsearch_version
  changed_when: false

- name: elasticsearch search guard plugin install
  shell: |
    /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch com.floragunn:search-guard-{{ elasticsearch_version.stdout|regex_replace('\..*', '') }}:{{ elasticsearch_version.stdout }}-{{ searchguard_version }}
  args:
    creates: "/usr/share/elasticsearch/plugins/search-guard-{{ elasticsearch_version.stdout|regex_replace('\\..*', '') }}"
  notify: elasticsearch restart
  register: result
  until: result | success
  retries: 3
  delay: 5

- block:
    - name: create keystore.jks
      command: "keytool -genkeypair -keystore /tmp/keystore.jks -storepass 'password' -keypass 'password' -dname 'CN=kirk,OU=client,O=client,L=test, C=de' -validity 3650"
      args:
        creates: /etc/elasticsearch/keystore.jks

    - name: keystore check
      shell: "cat /tmp/keystore.jks|base64 -w0"
      args:
        creates: /etc/elasticsearch/keystore.jks
      register: elasticsearch_keystore
      changed_when: false

    - name: delete temporary keystore.jks
      file:
        path: /tmp/keystore.jks
        state: absent

  run_once: true

- name: keystore deploy
  shell: "echo {{ elasticsearch_keystore.stdout|default() }}|base64 -d > /etc/elasticsearch/keystore.jks"
  args:
    creates: /etc/elasticsearch/keystore.jks
